### ISSUE TITLE
Confusing error message about finding unittest source

### ISSUE THREAD

**Issue by brettviren** [DUNE-DAQ/daq-buildtools#49]
In making a new package I made a `*_test.cpp` file under `unittest/` and get a misleading error message:

```
CMake Error at view-develop/lib/daq-buildtools/cmake/DAQ.cmake:239 (add_executable):
  Cannot find source file:

    unittest/FollyUri_test.cpp.cxx

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  filecmd/CMakeLists.txt:14 (daq_add_unit_test)


CMake Error at view-develop/lib/daq-buildtools/cmake/DAQ.cmake:239 (add_executable):
  No SOURCES given to target: FollyUri_test.cpp
Call Stack (most recent call first):
  filecmd/CMakeLists.txt:14 (daq_add_unit_test)
```

There is a hint of the real problem in that message and also the wiki docs eg:

 https://github.com/DUNE-DAQ/appfwk/wiki/Creating-a-new-package-under-v1.2.1 

use an example with `.cxx`.  Indeed I find in `DAQ.cmake` this extension is hard-wired 

https://github.com/DUNE-DAQ/daq-buildtools/blob/develop/cmake/DAQ.cmake#L239

Switching my test to use the extension to `.cxx` and all is well.

To save future time, it would be good to either support all the extensions in the error message or restrict the error message to just the extension(s) actually checked.

**Comment by alessandrothea** [comment]
Is this still an outstanding issue, or has it been fixed by the recent daq-buildtools releases?

**Comment by dingp** [comment]
Looking at the current `daq-cmake` code, it looks like the issue still stands.

**Comment by dingp** [comment]
We now have documentations specifying the naming conventions of unit test source file names. 

https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-cmake/#daq_add_unit_test
